name: C/C++ CI

on:
  push:
    branches: [ "main", "nemirko" ]
  pull_request:
    branches: [ "main", "nemirko" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        /usr/bin/git checkout --progress --force -B nemirko refs/remotes/origin/nemirko
        make
    - name: execute
      run: ./program.out
